name: Stable Build
on:
  push:
    branches:
    - main
    tags:
      - "*.*.*"
      - name: Set tag in env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          tags: runq/go-kube:${{ env.TAG }}, runq/go-kube:latest
