name: Stable Build
on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
jobs:
  workflow-main:
    name: Keel run on main branch
    runs-on: ubuntu-latest
    steps:
      - name: Set tag in env
        env:
          tags: amzarmuzani95/keel-test:${{ env.TAG }}, amzarmuzani95/keel-test:latest
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
