name: Docker Image CI for ghcr.io

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the Image
        run: |
          docker login --username amzarmuzani95 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/amzarmuzani95/keel-test-hello-world:latest
          docker push ghcr.io/amzarmuzani95/keel-test-hello-world:latest